In [1]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression

In [2]:
X_train = pd.read_csv("../dataset/X_train.csv")
X_test = pd.read_csv("../dataset/X_test.csv")

y_train = pd.read_csv("../dataset/y_train.csv").squeeze()
y_test = pd.read_csv("../dataset/y_test.csv").squeeze()

In [3]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (800000, 7)
X_test: (200000, 7)
y_train: (800000,)
y_test: (200000,)


In [4]:
log_reg = LogisticRegression(
    class_weight="balanced",
    random_state=42,
    max_iter=1000
)

In [5]:
log_reg.fit(X_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,'balanced'
,random_state,42
,solver,'lbfgs'
,max_iter,1000
,multi_class,'deprecated'


In [6]:
y_pred_lr = log_reg.predict(X_test)

In [7]:
y_pred_lr[:20]

array([0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [8]:
y_test[:20].values

array([0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [9]:
y_prob_lr = log_reg.predict_proba(X_test)[:, 1]

In [10]:
y_prob_lr[:20]

array([5.54480452e-02, 8.39974711e-01, 2.28998940e-02, 3.42374612e-02,
       2.53005351e-02, 6.45009828e-01, 9.98563738e-01, 3.41036219e-01,
       2.50090368e-03, 3.74465045e-02, 1.13020192e-01, 9.27415498e-03,
       2.21593130e-03, 1.13677461e-01, 1.91143014e-03, 6.42153135e-05,
       2.56029371e-03, 1.42174440e-03, 1.41191730e-01, 2.91786463e-05])

In [11]:
pd.Series(y_pred_lr).value_counts()

0.0    163145
1.0     36855
Name: count, dtype: int64

In [12]:
pd.Series(y_pred_lr).value_counts(normalize=True) * 100

0.0    81.5725
1.0    18.4275
Name: proportion, dtype: float64

In [13]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score
)

In [14]:
accuracy = accuracy_score(y_test, y_pred_lr)
print("Accuracy:", accuracy)

Accuracy: 0.88661


In [15]:
precision = precision_score(y_test, y_pred_lr)
recall = recall_score(y_test, y_pred_lr)
f1 = f1_score(y_test, y_pred_lr)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Precision: 0.4294939628272962
Recall: 0.9054973971740747
F1 Score: 0.5826339811542992


In [16]:
cm = confusion_matrix(y_test, y_pred_lr)
print(cm)

[[161493  21026]
 [  1652  15829]]


In [17]:
tn, fp, fn, tp = cm.ravel()

print("True Negatives:", tn)
print("False Positives:", fp)
print("False Negatives:", fn)
print("True Positives:", tp)

True Negatives: 161493
False Positives: 21026
False Negatives: 1652
True Positives: 15829


In [18]:
print(classification_report(y_test, y_pred_lr))

              precision    recall  f1-score   support

         0.0       0.99      0.88      0.93    182519
         1.0       0.43      0.91      0.58     17481

    accuracy                           0.89    200000
   macro avg       0.71      0.90      0.76    200000
weighted avg       0.94      0.89      0.90    200000



In [19]:
roc_auc = roc_auc_score(y_test, y_prob_lr)
print("ROC-AUC:", roc_auc)

ROC-AUC: 0.9639103583389532


In [20]:
print("Logistic Regression Results")
print("--------------------------")
print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)
print("ROC-AUC  :", roc_auc)

Logistic Regression Results
--------------------------
Accuracy : 0.88661
Precision: 0.4294939628272962
Recall   : 0.9054973971740747
F1 Score : 0.5826339811542992
ROC-AUC  : 0.9639103583389532


In [21]:
from sklearn.tree import DecisionTreeClassifier

In [22]:
decision_tree = DecisionTreeClassifier(
    class_weight="balanced",
    random_state=42,
    max_depth=10
)

In [23]:
decision_tree.fit(X_train, y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,10
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,42
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,'balanced'


In [24]:
y_pred_dt = decision_tree.predict(X_test)

In [25]:
y_prob_dt = decision_tree.predict_proba(X_test)[:, 1]

In [26]:
pd.Series(y_pred_dt).value_counts()

0.0    182520
1.0     17480
Name: count, dtype: int64

In [27]:
pd.Series(y_pred_dt).value_counts(normalize=True) * 100

0.0    91.26
1.0     8.74
Name: proportion, dtype: float64

In [28]:
print("Tree depth:", decision_tree.get_depth())

Tree depth: 8


In [29]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score
)

# Calculate metrics
accuracy_dt = accuracy_score(y_test, y_pred_dt)
precision_dt = precision_score(y_test, y_pred_dt)
recall_dt = recall_score(y_test, y_pred_dt)
f1_dt = f1_score(y_test, y_pred_dt)
roc_auc_dt = roc_auc_score(y_test, y_prob_dt)

# Print results
print("Decision Tree Results")
print("---------------------")
print("Accuracy :", accuracy_dt)
print("Precision:", precision_dt)
print("Recall   :", recall_dt)
print("F1 Score :", f1_dt)
print("ROC-AUC  :", roc_auc_dt)

Decision Tree Results
---------------------
Accuracy : 0.999985
Precision: 0.9999427917620137
Recall   : 0.999885590069218
F1 Score : 0.9999141900975372
ROC-AUC  : 0.9999400555937836


In [30]:
cm_dt = confusion_matrix(y_test, y_pred_dt)

print("\nConfusion Matrix:")
print(cm_dt)

tn_dt, fp_dt, fn_dt, tp_dt = cm_dt.ravel()

print("\nTrue Negatives :", tn_dt)
print("False Positives:", fp_dt)
print("False Negatives:", fn_dt)
print("True Positives :", tp_dt)


Confusion Matrix:
[[182518      1]
 [     2  17479]]

True Negatives : 182518
False Positives: 1
False Negatives: 2
True Positives : 17479


In [31]:
print("\nClassification Report:")
print(classification_report(y_test, y_pred_dt))


Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    182519
         1.0       1.00      1.00      1.00     17481

    accuracy                           1.00    200000
   macro avg       1.00      1.00      1.00    200000
weighted avg       1.00      1.00      1.00    200000



In [32]:
print("\nFeature Importances:")
print(
    pd.Series(
        decision_tree.feature_importances_,
        index=X_train.columns
    ).sort_values(ascending=False)
)


Feature Importances:
ratio_to_median_purchase_price    0.513988
distance_from_home                0.276522
distance_from_last_transaction    0.112135
online_order                      0.049210
used_chip                         0.028575
used_pin_number                   0.016434
repeat_retailer                   0.003136
dtype: float64


In [33]:
full_df = pd.read_csv("/Users/cepl/Documents/Machine_Learning/Credit-Card-Fraud-Detection/dataset/card_transdata.csv")

print(full_df.groupby("fraud").mean(numeric_only=True).T)

fraud                                 0.0        1.0
distance_from_home              22.832976  66.261876
distance_from_last_transaction   4.301391  12.712185
ratio_to_median_purchase_price   1.423642   6.006323
repeat_retailer                  0.881672   0.880119
used_chip                        0.359402   0.256399
used_pin_number                  0.109944   0.003123
online_order                     0.622225   0.946318


In [34]:
from sklearn.ensemble import RandomForestClassifier

random_forest = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

random_forest.fit(X_train, y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,10
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [36]:
random_forest.fit(X_train, y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,10
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [37]:
y_pred_rf = random_forest.predict(X_test)

In [38]:
y_prob_rf = random_forest.predict_proba(X_test)[:, 1]

In [39]:
print("First 20 predictions:")
print(y_pred_rf[:20])

print("\nFirst 20 actual values:")
print(y_test[:20].values)

print("\nFirst 20 fraud probabilities:")
print(y_prob_rf[:20])

First 20 predictions:
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

First 20 actual values:
[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

First 20 fraud probabilities:
[2.89295948e-02 9.70923609e-01 6.26421428e-03 4.36439320e-02
 5.78042744e-03 3.81651470e-02 9.94664206e-01 3.04952015e-02
 0.00000000e+00 6.26421428e-03 0.00000000e+00 3.63991245e-02
 1.09573309e-02 2.89295948e-02 1.13113989e-02 0.00000000e+00
 1.02051314e-05 0.00000000e+00 2.88488977e-02 0.00000000e+00]


In [40]:
print("\nPrediction distribution:")
print(pd.Series(y_pred_rf).value_counts())

print("\nPrediction percentages:")
print(pd.Series(y_pred_rf).value_counts(normalize=True) * 100)


Prediction distribution:
0.0    182524
1.0     17476
Name: count, dtype: int64

Prediction percentages:
0.0    91.262
1.0     8.738
Name: proportion, dtype: float64


In [41]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

accuracy = accuracy_score(y_test, y_pred_rf)
precision = precision_score(y_test, y_pred_rf)
recall = recall_score(y_test, y_pred_rf)
f1 = f1_score(y_test, y_pred_rf)
roc_auc = roc_auc_score(y_test, y_prob_rf)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)
print("ROC-AUC  :", roc_auc)

Accuracy : 0.999975
Precision: 1.0
Recall   : 0.999713975173045
F1 Score : 0.9998569671310468
ROC-AUC  : 0.9999999899705844


In [42]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_rf)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[182519      0]
 [     5  17476]]


In [43]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    182519
         1.0       1.00      1.00      1.00     17481

    accuracy                           1.00    200000
   macro avg       1.00      1.00      1.00    200000
weighted avg       1.00      1.00      1.00    200000



In [44]:
feature_importance_rf = pd.Series(
    random_forest.feature_importances_,
    index=X_train.columns
).sort_values(ascending=False)

print("Feature Importance:")
print(feature_importance_rf)

Feature Importance:
ratio_to_median_purchase_price    0.545220
distance_from_home                0.196829
online_order                      0.112928
distance_from_last_transaction    0.076125
used_pin_number                   0.034175
used_chip                         0.025409
repeat_retailer                   0.009314
dtype: float64


In [45]:
model_comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest"
    ],
    "Accuracy": [
        accuracy_score(y_test, y_pred_lr),
        accuracy_score(y_test, y_pred_dt),
        accuracy_score(y_test, y_pred_rf)
    ],
    "Precision": [
        precision_score(y_test, y_pred_lr),
        precision_score(y_test, y_pred_dt),
        precision_score(y_test, y_pred_rf)
    ],
    "Recall": [
        recall_score(y_test, y_pred_lr),
        recall_score(y_test, y_pred_dt),
        recall_score(y_test, y_pred_rf)
    ],
    "F1 Score": [
        f1_score(y_test, y_pred_lr),
        f1_score(y_test, y_pred_dt),
        f1_score(y_test, y_pred_rf)
    ],
    "ROC-AUC": [
        roc_auc_score(y_test, y_prob_lr),
        roc_auc_score(y_test, y_prob_dt),
        roc_auc_score(y_test, y_prob_rf)
    ]
})

model_comparison

,Model,Accuracy,Precision,Recall,F1 Score,ROC-AUC
0,Logistic Regression,0.886610,0.429494,0.905497,0.582634,0.96391
1,Decision Tree,0.999985,0.999943,0.999886,0.999914,0.99994
2,Random Forest,0.999975,1.000000,0.999714,0.999857,1.00000


In [46]:
import joblib

joblib.dump(log_reg, "../dataset/logistic_regression.pkl")
joblib.dump(decision_tree, "../dataset/decision_tree.pkl")
joblib.dump(random_forest, "../dataset/random_forest.pkl")

['../dataset/random_forest.pkl']